---
- name: Download nginx and deploy html
  hosts: node
  tasks:
    - name: Update and upgrade apt packages
      yum:
        name: "*"
        state: latest
    - name: Nginx install
      yum:
        name: nginx
        state: present
    - name: start nginx
      service:
        name: nginx
        state: started
    - name: copy the code to target server
      copy:
        src: /home/ec2-user/jenkins-node/workspace/ansible-pipeline/web.zip
        dest: /home/ec2-user/web.zip
    - name: Unarchive a file that is already on the remote machine
      unarchive:
        src: /home/ec2-user/web.zip
        dest: /usr/share/nginx/html/
        remote_src: yes
    - name: start nginx
      service:
        name: nginx
        state: restarted
